"""proactive_sdk — proactive personal agent runtime kernel (PAS).

Design-stage package. P0 froze contracts, path safety and schema
validation; P1 adds the persistence layer (store, migrations, clock,
schedules, misfire, claim/fencing, jobs API); P2 adds the hook runtime
(legacy protocol parser, sandbox runner, staging + CAS state machine,
dry-run); P3 adds the independent agent loop (typed source/memory ports,
ContextPack, bounded ToolLoopExecutor, OpenAI-compatible ModelPort,
L0/L1 coordinator); P4 adds the policy & delivery layer (grants,
frozen-parameter approvals, owner channels, outbox dispatcher with
attempt journal and unknown reconciliation, local inbox, real webhook
notification sink, feedback). Importing this package must never start
threads, daemons or I/O.
"""

from __future__ import annotations

PAS_PROTOCOL_VERSION = "1.0"
__version__ = "0.1.2"

from .clock import Clock, FakeClock, SystemClock
from .contracts import (
    ActionProposal,
    ContextPack,
    ContextSource,
    Decision,
    ErrorCode,
    ExecutorCapabilities,
    JobSpec,
    MemoryEntry,
    ModelRequest,
    ModelResponse,
    ModelToolCall,
    PASError,
    ProfileConfig,
    RunBudget,
    RunRequest,
    RuntimeConfig,
    SourceBatch,
    SourceItem,
    SourceRequest,
    assert_single_profile,
    canonical_json,
    content_hash,
    error_for_code,
    require_utc_timestamp,
    OBLIGATION_DUE,
    OBLIGATION_OPPORTUNISTIC,
    OBLIGATIONS,
    REMINDER_KEYS,
    NOTIFY_SELF_CAPABILITY,
    default_obligation,
    validate_context_pack,
    validate_decision,
    validate_reminder,
    validate_schedule,
)
from .context import (
    ContextPackBuilder,
    EphemeralMemoryPort,
    MemoryPort,
    SnapshotMaterializer,
    SourceEntry,
    SourceRegistry,
    render_context_blocks,
)
from .coordinator import CoordinatorConfig, ProactiveCoordinator, RunReport
from .delivery import (
    DeliveryRequest,
    DispatchConfig,
    DispatchReport,
    FeedbackManager,
    OutboxDispatcher,
    ReconcileAnswer,
    ReconcileRequest,
    SinkResult,
    WebhookNotificationSink,
)
from .decision_contract import (
    CONTRACT_RULES,
    DECISION_CONTRACT_VERSION,
    KIND_ENUM,
    ContractRule,
    agent_system_prompt,
    decision_contract,
)
from .host_forms import CallableHostDriver, SubprocessHostDriver, extract_envelope
from .host_drivers import HermesHostDriver, PiHostDriver
from .host_bridge import (
    CANCEL_CONFIRMED,
    CANCEL_REQUESTED,
    CANCEL_UNSUPPORTED,
    HOST_CANCEL_LEVELS,
    HostBridge,
    HostDriver,
    HostPrompt,
    HostReply,
)
from .contracts import (
    TOOL_AUTHORITIES,
    TOOL_AUTHORITY_HOST,
    TOOL_AUTHORITY_PAS_BROKER,
    TOOL_AUTHORITY_UNKNOWN,
)
from .executor import (
    ExecutorConfig,
    ExecutorContext,
    ExecutorOutcome,
    RunCancelled,
    RunExecutor,
    ToolLoopExecutor,
)
from .hooks import (
    BubblewrapSandbox,
    HookProtocolError,
    HookResult,
    HookRunner,
    HookRunnerConfig,
    HookRunReport,
    HookRunSummary,
    HookSandbox,
    HookSpec,
    PlainSubprocessSandbox,
    SeatbeltSandbox,
    parse_hook_logs,
    parse_hook_result,
    platform_sandbox,
)
from .model import OpenAICompatibleModel
from .pathsafe import (
    PathSafetyError,
    ensure_within,
    safe_join,
    validate_zip_member,
)
from .policy import (
    NOTIFY_SELF_CAPABILITY,
    POLICY_VERSION,
    ApprovalManager,
    GrantManager,
    OwnerChannelRegistry,
    PolicyConfig,
    PolicyEngine,
    PolicyRunReport,
    quiet_end_ms,
)
from .scheduler import (
    AdmissionReport,
    Schedule,
    Scheduler,
    latest_due_slot,
    next_occurrence_after,
    parse_schedule,
    resolve_local_wall,
)
from .store import (
    ApprovalRecord,
    EventRecord,
    GrantRecord,
    HookClaim,
    HookCommitResult,
    HookRecord,
    JobRecord,
    OutboxLease,
    ReminderAdmission,
    RunLease,
    SnapshotRecord,
    SourceStateRecord,
    Store,
)
from .windows import local_day_end_ms, local_day_start_ms, quiet_window
from .tools import (
    AuthorizedToolCall,
    BrokerCallContext,
    LocalToolBroker,
    ToolCallAttempt,
    ToolResult,
    ToolSpec,
)
from .builtin_tools import (
    CAPABILITY_MEMORY_READ,
    CAPABILITY_STATE_READ,
    builtin_tools,
)
from .toolkit import Tool, register_tools, schema_for_type, tool
from .config import (
    CONFIG_VERSION,
    ControlPlaneSection,
    HeartbeatSection,
    PasConfig,
    PolicySection,
    RuntimeSection,
    SkillsSection,
    build_config,
    config_to_yaml_subset,
    load_config,
    parse_config_text,
)
from .observability import (
    Metrics,
    StructuredLogger,
    contains_unredacted_secret,
    free_disk_mb,
    health_snapshot,
    redact_text,
)
from .backup import BackupError, create_backup, read_backup_meta, restore_backup
from .facade import ChannelSink, Job, ProactiveAgent

__all__ = [
    "PAS_PROTOCOL_VERSION",
    "__version__",
    # P0 contracts
    "ErrorCode",
    "PASError",
    "ProfileConfig",
    "RuntimeConfig",
    "JobSpec",
    "assert_single_profile",
    "canonical_json",
    "content_hash",
    "error_for_code",
    "require_utc_timestamp",
    "validate_decision",
    "validate_context_pack",
    "validate_schedule",
    "PathSafetyError",
    "ensure_within",
    "safe_join",
    "validate_zip_member",
    # P1 clock
    "Clock",
    "SystemClock",
    "FakeClock",
    # P1 store
    "Store",
    "JobRecord",
    "RunLease",
    "EventRecord",
    "SourceStateRecord",
    "SnapshotRecord",
    # P1 scheduler
    "Schedule",
    "Scheduler",
    "AdmissionReport",
    "parse_schedule",
    "resolve_local_wall",
    "latest_due_slot",
    "next_occurrence_after",
    # P2 hooks
    "HookSpec",
    "HookResult",
    "HookProtocolError",
    "HookRunner",
    "HookRunnerConfig",
    "HookRunReport",
    "HookRunSummary",
    "HookSandbox",
    "PlainSubprocessSandbox",
    "SeatbeltSandbox",
    "BubblewrapSandbox",
    "platform_sandbox",
    "parse_hook_result",
    "parse_hook_logs",
    "HookRecord",
    "HookClaim",
    "HookCommitResult",
    # P3 contracts (typed records)
    "ActionProposal",
    "ContextPack",
    "ContextSource",
    "Decision",
    "ExecutorCapabilities",
    "MemoryEntry",
    "ModelRequest",
    "ModelResponse",
    "ModelToolCall",
    "RunBudget",
    "RunRequest",
    "SourceBatch",
    "SourceItem",
    "SourceRequest",
    # P3 context
    "ContextPackBuilder",
    "EphemeralMemoryPort",
    "MemoryPort",
    "SnapshotMaterializer",
    "SourceEntry",
    "SourceRegistry",
    "render_context_blocks",
    # P3 model / tools / executor / coordinator
    "OpenAICompatibleModel",
    "Tool",
    "tool",
    "register_tools",
    "schema_for_type",
    "builtin_tools",
    "CAPABILITY_MEMORY_READ",
    "CAPABILITY_STATE_READ",
    "AuthorizedToolCall",
    "BrokerCallContext",
    "LocalToolBroker",
    "ToolCallAttempt",
    "ToolResult",
    "ToolSpec",
    "ExecutorConfig",
    "ExecutorOutcome",
    "RunCancelled",
    "ToolLoopExecutor",
    "CoordinatorConfig",
    "ProactiveCoordinator",
    "RunReport",
    # P4 policy & delivery
    "POLICY_VERSION",
    "NOTIFY_SELF_CAPABILITY",
    "PolicyConfig",
    "PolicyEngine",
    "PolicyRunReport",
    "GrantManager",
    "OwnerChannelRegistry",
    "ApprovalManager",
    "quiet_end_ms",
    "quiet_window",
    "local_day_start_ms",
    "local_day_end_ms",
    "ReminderAdmission",
    "ExecutorContext",
    "RunExecutor",
    "TOOL_AUTHORITIES",
    "TOOL_AUTHORITY_HOST",
    "TOOL_AUTHORITY_PAS_BROKER",
    "TOOL_AUTHORITY_UNKNOWN",
    "DECISION_CONTRACT_VERSION",
    "HostBridge",
    "HermesHostDriver",
    "CallableHostDriver",
    "SubprocessHostDriver",
    "extract_envelope",
    "PiHostDriver",
    "HostDriver",
    "HostPrompt",
    "HostReply",
    "CANCEL_CONFIRMED",
    "CANCEL_REQUESTED",
    "CANCEL_UNSUPPORTED",
    "HOST_CANCEL_LEVELS",
    "decision_contract",
    "agent_system_prompt",
    "CONTRACT_RULES",
    "KIND_ENUM",
    "validate_reminder",
    "REMINDER_KEYS",
    "OBLIGATIONS",
    "OBLIGATION_DUE",
    "OBLIGATION_OPPORTUNISTIC",
    "default_obligation",
    "GrantRecord",
    "ApprovalRecord",
    "OutboxLease",
    "DeliveryRequest",
    "ReconcileRequest",
    "SinkResult",
    "ReconcileAnswer",
    "WebhookNotificationSink",
    "DispatchConfig",
    "DispatchReport",
    "OutboxDispatcher",
    "FeedbackManager",
    # P7 config
    "CONFIG_VERSION",
    "PasConfig",
    "RuntimeSection",
    "HeartbeatSection",
    "PolicySection",
    "SkillsSection",
    "ControlPlaneSection",
    "build_config",
    "load_config",
    "parse_config_text",
    "config_to_yaml_subset",
    # P7 observability
    "Metrics",
    "StructuredLogger",
    "redact_text",
    "contains_unredacted_secret",
    "health_snapshot",
    "free_disk_mb",
    # P7 backup
    "BackupError",
    "create_backup",
    "read_backup_meta",
    "restore_backup",
    # P7 facade
    "ProactiveAgent",
    "Job",
    "ChannelSink",
]
