#!/usr/bin/env python3
"""Generate packages/client-ts/src/schema_types.ts from schemas/v1/*.json.

One source of truth for the wire shapes: the TypeScript side is generated,
never hand-copied, so a schema change (e.g. P1's ``fold_policy``) lands in
both languages at once. Re-run after any schemas/v1 change; the contract
test test_client_ts.py fails when the committed file drifts.

Supported keywords are the closed set used by schemas/v1 (see
schemas/README.md): type/enum/const/items/$ref/$defs/required/min-max
bounds/additionalProperties (annotation only). Formats are validated
Python-side, not in TS.
"""

from __future__ import annotations

import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SCHEMA_DIR = ROOT / "schemas" / "v1"
OUT_FILE = ROOT / "packages" / "client-ts" / "src" / "schema_types.ts"

HEADER = """\
// GENERATED by tools/gen_client_ts.py from schemas/v1 — do not edit.
// Regenerate: python3 tools/gen_client_ts.py
// Wire field names are snake_case by design; do not camelCase them.
"""


def _ts_type(node: dict, defs: dict, indent: str) -> str:
    if not node:
        return "unknown"  # bare "items": {} etc. — unconstrained
    if "const" in node:
        return json.dumps(node["const"])
    if "enum" in node:
        return " | ".join(json.dumps(v) for v in node["enum"])
    if "$ref" in node:
        name = node["$ref"]
        if not name.startswith("#/$defs/"):
            raise SystemExit(f"unsupported $ref {name}")
        return _pascal(name.split("/")[-1])
    if "type" not in node:
        raise SystemExit(f"schema node without type/enum/const/$ref: {node!r}")
    raw = node["type"]
    variants = raw if isinstance(raw, list) else [raw]
    base: list[str] = []
    nullable = "null" in variants
    for variant in variants:
        if variant == "null":
            continue
        if variant == "string":
            base.append("string")
        elif variant in ("integer", "number"):
            base.append("number")
        elif variant == "boolean":
            base.append("boolean")
        elif variant == "array":
            base.append(f"ReadonlyArray<{_ts_type(node.get('items', {}), defs, indent)}>")
        elif variant == "object":
            if "properties" in node:
                base.append(_inline_object(node, defs, indent))
            else:
                base.append("Record<string, unknown>")
        else:
            raise SystemExit(f"unsupported type {variant!r}")
    if not base:
        base.append("unknown")
    joined = " | ".join(base)
    return f"{joined} | null" if nullable else joined


def _inline_object(node: dict, defs: dict, indent: str) -> str:
    required = set(node.get("required", []))
    props = node.get("properties", {})
    inner = indent + "  "
    lines = ["{"]
    for name, spec in props.items():
        optional = "" if name in required else "?"
        doc = f"{inner}/** {str(spec.get('description', ''))[:160]} */\n" if spec.get("description") else ""
        lines.append(f"{inner}{doc}{json.dumps(name)}{optional}: {_ts_type(spec, defs, inner)};")
    lines.append(indent + "}")
    return "\n".join(lines)


def _pascal(name: str) -> str:
    return re.sub(r"[^A-Za-z0-9]", "", name[:1].upper() + name[1:])


def _interface_name(schema: dict, path: Path) -> str:
    title = schema.get("title") or path.stem
    name = _pascal(title)
    if name in ("Error", "PASError"):
        name = "PasError"  # avoid clashing with the TS built-in
    return name


def generate() -> str:
    blocks: list[str] = [HEADER]
    emitted_defs: set[str] = set()
    for path in sorted(SCHEMA_DIR.glob("*.json")):
        schema = json.loads(path.read_text(encoding="utf-8"))
        defs = schema.get("$defs", {})
        name = _interface_name(schema, path)
        description = str(schema.get("description", "")).replace("\n", " ")
        required = set(schema.get("required", []))
        lines = [f"// {path.name}: {description}"]
        if schema.get("additionalProperties") is False:
            lines.append("// Closed object: additionalProperties is false on the wire.")
        lines.append(f"export interface {name} {{")
        for prop, spec in schema.get("properties", {}).items():
            optional = "" if prop in required else "?"
            doc = spec.get("description")
            if doc:
                lines.append(f"  /** {str(doc)[:160]} */")
            lines.append(f"  {json.dumps(prop)}{optional}: {_ts_type(spec, defs, '  ')};")
        lines.append("}")
        blocks.append("\n".join(lines))
        for def_name, def_node in defs.items():
            if def_name in emitted_defs:
                continue  # shared defs (protocol_version) emit once, globally
            emitted_defs.add(def_name)
            def_type = _ts_type(def_node, defs, "  ")
            doc = str(def_node.get("description", ""))
            header = f"// {def_name}: {doc}" if doc else f"// {def_name}"
            blocks.append(f"{header}\nexport type {_pascal(def_name)} = {def_type};")
    return "\n\n".join(blocks) + "\n"


def main() -> int:
    output = generate()
    OUT_FILE.parent.mkdir(parents=True, exist_ok=True)
    if OUT_FILE.exists() and OUT_FILE.read_text(encoding="utf-8") == output:
        print(f"unchanged: {OUT_FILE}")
        return 0
    OUT_FILE.write_text(output, encoding="utf-8")
    print(f"wrote {OUT_FILE}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
