// GENERATED by tools/gen_client_ts.py from schemas/v1 — do not edit.
// Regenerate: python3 tools/gen_client_ts.py
// Wire field names are snake_case by design; do not camelCase them.


// action_record.json: SPEC §4.1 ActionRecord. canonical_arguments_hash is the SHA-256 of the canonical JSON of the frozen action arguments; approvals bind this hash, not a verbal category (SPEC §9.2).
// Closed object: additionalProperties is false on the wire.
export interface ActionRecord {
  "protocol_version": Protocolversion;
  "action_id": string;
  "kind": "notify_self" | "draft" | "internal_record" | "suggest_watch" | "request_external_action";
  "canonical_arguments_hash": string;
  "grant_id"?: string | null;
  "approval_id"?: string | null;
  "policy_version"?: string;
  "state": "planned" | "approved" | "queued" | "executed" | "failed" | "cancelled" | "reconciled";
  "fact_id"?: string | null;
  "created_at"?: string;
}

// protocol_version
export type Protocolversion = string;

// context_pack.json: SPEC §4.1 / §7.1 ContextPack. Immutable snapshot for one run. All ids and timestamps in documents using this schema are fake examples unless issued by a live system. recent_notifications is the bounded, redacted summary of notifications already sent in the last 24 h (SPEC §21.1 step 6); it exists so a model can compare topics, openings and fact deltas, and it never carries a message body.
// Closed object: additionalProperties is false on the wire.
export interface ContextPack {
  "schema_version": "1.0";
  "task": {
    "goal_id": string;
    "scope": string;
  };
  "locale": string;
  "timezone": string;
  "preferences_ref": string;
  "sources": ReadonlyArray<Sourcesnapshot>;
  "pending_refs": ReadonlyArray<string>;
  "sent_fact_refs": ReadonlyArray<string>;
  "memory_refs": ReadonlyArray<string>;
  "untrusted_content_policy": "data_only";
  /** Already-sent notifications from the last 24 h, reduced to non-sensitive fields. Hard-dedup stays with the business key; this summary only lets a model compare t */
  "recent_notifications"?: ReadonlyArray<Recentnotification>;
}

// recent_notification: One already-sent notification reduced to non-sensitive fields. There is deliberately no body field: redaction is structural, not best-effort.
export type Recentnotification = {
        /** Short digest of the fact id: comparable across messages, but not a ledger key. */
"fact_digest": string;
    "channel_kind": "local_inbox" | "webhook";
    "topic"?: string;
    "title": string;
    "sent_at_ms": number;
  };

// source_snapshot
export type Sourcesnapshot = {
    "source_id": string;
    "account_ref": string;
    "snapshot_ref": string;
    "observed_at": string;
    "fresh_until": string;
    "sensitivity": "public" | "private" | "sensitive";
  };

// decision.json: SPEC §4.1 / §8.1 Decision with ActionProposal definitions. Unknown fields, oversized bodies and unsupported kinds are rejected. Cross-field rules (silent=>no proposals, propose=>>=1 proposal, notify_self needs evidence_refs+expires_at) are enforced by contracts.validate_decision.
// Closed object: additionalProperties is false on the wire.
export interface Decision {
  "protocol_version": Protocolversion;
  "decision": "propose" | "silent";
  "summary": string;
  "proposals": ReadonlyArray<Actionproposal>;
}

// action_proposal
export type Actionproposal = {
    "kind": "notify_self" | "draft" | "internal_record" | "suggest_watch" | "request_external_action";
    "fact_id": string;
    "revision": string;
    "body"?: string;
    "arguments"?: Record<string, unknown>;
    "evidence_refs"?: ReadonlyArray<string>;
    "expires_at"?: string;
  };

// delivery_attempt.json: SPEC §4.1 DeliveryAttempt with the §10.2 outbox state machine. delivery_unknown is never auto-retried; late receipts are reconciled, not discarded.
// Closed object: additionalProperties is false on the wire.
export interface DeliveryAttempt {
  "protocol_version": Protocolversion;
  "message_id": string;
  "attempt_id": string;
  "fence": number;
  "provider_key": string;
  "state": "pending" | "sending" | "provider_accepted" | "stored_in_inbox" | "failed_retryable" | "failed_terminal" | "delivery_unknown" | "deferred" | "suppressed" | "expired" | "reconciled_delivered";
  "receipt"?: {
    "external_id"?: string | null;
    "received_at"?: string | null;
  } | null;
  "last_error_class"?: string | null;
  "not_before"?: string | null;
}

// error.json: SPEC §4.4 unified error envelope. Carries safe fields only; tokens, mail bodies and raw HTTP bodies must never be placed in safe_message.
// Closed object: additionalProperties is false on the wire.
export interface PasError {
  "protocol_version": Protocolversion;
  "code": "invalid_config" | "unsupported_capability" | "dependency_missing" | "permission_denied" | "approval_required" | "auth_required" | "rate_limited" | "budget_exceeded" | "deadline_exceeded" | "stale_context" | "provider_unavailable" | "conflict" | "effect_unknown" | "internal_error";
  "safe_message": string;
  "retryable": boolean;
  "retry_after_s"?: number;
  "scope"?: "request" | "run" | "job" | "profile" | "provider";
  "correlation_id": string;
}

// job_spec.json: SPEC §4.1 JobSpec. Per-kind required schedule fields (interval=>anchor+every_seconds; daily/monthly=>local_time+timezone; weekly=>weekdays+local_time+timezone; runonce=>at) are enforced in contracts.validate_schedule, not in this schema. DST/fold policy persists per job revision (SPEC §5.1). mode=reminder is the deterministic direct reminder (SPEC §21.1 step 2): it carries a frozen reminder block instead of task.instruction, performs no model call, and is validated in contracts.validate_reminder.
// Closed object: additionalProperties is false on the wire.
export interface JobSpec {
  "protocol_version": Protocolversion;
  "job_id": string;
  "revision": number;
  "owner": "pas" | "host";
  /** heartbeat = opportunistic check; task = explicit agent task; reminder = deterministic direct reminder delivered at the scheduled instant with zero model calls ( */
  "mode": "heartbeat" | "task" | "reminder";
  "schedule": Schedule;
  "task": {
    "instruction": string;
    "goal_id"?: string;
    "skill_refs"?: ReadonlyArray<string>;
  };
  "grant_refs"?: ReadonlyArray<string>;
  "delivery_policy"?: {
    "notification_profile"?: string;
    "quiet_hours_respected"?: boolean;
    "expire_after_s"?: number;
  };
  "misfire_policy"?: "coalesce_latest" | "grace_once" | "expire";
  "deadline"?: string;
  "enabled": boolean;
  "reminder"?: Reminder;
  /** Notification obligation granted by trusted task configuration (SPEC §21.1 step 3). 'due' means the job owes a notification at its scheduled instant and any defe */
  "obligation"?: "due" | "opportunistic";
}

// reminder: Frozen user-authored reminder text (SPEC §21.1 step 2). Nothing here comes from model output or source content; the body, instants, zone, owner channel and obligation are all frozen by the trusted jobs_upsert path.
export type Reminder = {
    "title"?: string;
        /** The exact text the owner will receive. Must contain every artifact_refs entry verbatim, so the owner can open what the message names (SPEC §21.1 step 8). */
"body": string;
        /** IANA zone the user froze this reminder in; must equal schedule.timezone when the schedule declares one. */
"timezone": Timezone;
        /** Owner channel ref. Omitted means the profile's bound owner destination. Any other value must be a registered owner channel: a reminder can never invent a receiv */
"destination"?: string;
    "topic"?: string;
        /** Source ids re-read right before the message goes out (SPEC §21.1 step 5). A reminder that declares none is sent exactly as frozen. */
"refresh_sources"?: ReadonlyArray<string>;
        /** Facts this reminder is about; a tombstoned one cancels the message before it is sent (SPEC §21.1 step 5). */
"fact_refs"?: ReadonlyArray<string>;
        /** Openable local artifact references (artifact:<relative path>, no absolute or machine-local paths). Each must appear verbatim in the body. */
"artifact_refs"?: ReadonlyArray<string>;
  };

// timezone: IANA zone name; never a machine-local inference (SPEC §14.3).
export type Timezone = string;

// schedule
export type Schedule = {
    "kind": "interval" | "daily" | "weekly" | "monthly" | "runonce";
    "anchor"?: string;
    "every_seconds"?: number;
    "local_time"?: string;
    "timezone"?: Timezone;
    "weekdays"?: ReadonlyArray<number>;
    "day_of_month"?: number;
    "at"?: string;
        /** DST fall-back repetition choice for daily/weekly/monthly (SPEC §5.1); persists per job revision. Spring-forward gaps are always skipped, independent of this fie */
"fold_policy"?: "earliest" | "latest";
  };

// run_handle.json: SPEC §4.1 RunHandle. Declared capabilities are claims, not proof: conformance tests and deployment-side isolation checks remain mandatory (SPEC §4.2).
// Closed object: additionalProperties is false on the wire.
export interface RunHandle {
  "protocol_version": Protocolversion;
  "executor_id": string;
  "host_run_id"?: string | null;
  "state": "accepted" | "running" | "waiting_for_approval" | "completed" | "failed" | "cancelled";
  "resume_token"?: string | null;
  "capabilities": ReadonlyArray<"streaming" | "cancellation" | "resumption" | "external_tool_broker" | "read_only_enforcement" | "usage_reporting">;
}

// run_request.json: SPEC §4.1 RunRequest. The fence is monotonic per run and must be re-checked on every commit; an old fence must not be able to submit (SPEC §10.3).
// Closed object: additionalProperties is false on the wire.
export interface RunRequest {
  "protocol_version": Protocolversion;
  "run_id": string;
  "attempt": number;
  "fence": number;
  "context_ref": string;
  "skill_refs"?: ReadonlyArray<string>;
  "tool_allowlist"?: ReadonlyArray<string>;
  "budget": Budget;
  "deadline": string;
  "policy_version": string;
}

// budget
export type Budget = {
    "max_model_turns": number;
    "max_tool_calls": number;
    "wall_time_s": number;
    "max_proposals": number;
  };

// usage.json: SPEC §4.1 Usage. Unmeasurable values are null, never zero; pricing_basis records how numbers were obtained.
// Closed object: additionalProperties is false on the wire.
export interface Usage {
  "protocol_version": Protocolversion;
  "provider": string;
  "model": string;
  "input_tokens": number | null;
  "output_tokens": number | null;
  "cache_read_tokens"?: number | null;
  "tool_calls": number | null;
  "elapsed_ms": number | null;
  "pricing_basis": "measured" | "estimated" | "unknown";
}

// wake_event.json: SPEC §4.1 WakeEvent. A wake is not a notification and not a run; it is a deduplicated candidate signal admitted into the EventStore (SPEC §5).
// Closed object: additionalProperties is false on the wire.
export interface WakeEvent {
  "protocol_version": Protocolversion;
  "event_id": string;
  "origin": "scheduler" | "hook" | "manual" | "host_delegate";
  "occurrence_id": string;
  "observed_at": string;
  "expires_at": string;
  "source_refs"?: ReadonlyArray<string>;
  "cause": string;
  "dedupe_key": string;
  /** Legacy hook mode keeps arbitrary JSON values (SPEC §6.1); new envelope events should attach typed refs instead. */
  "payload"?: Record<string, unknown> | ReadonlyArray<unknown> | string | number | boolean | null;
}
